project:
  type: website
  pre-render: scripts/generate-templates.sh

website:
  title: "Quarto Vitae"
  description: "Quarto extensions for writing CVs and résumés."
  site-url: "https://quarto-vitae.github.io"
  repo-url: "https://github.com/quarto-vitae/quarto-vitae.github.io"
  repo-actions: [issue]
  open-graph:
    image: images/opengraph.png
  twitter-card:
    image: images/opengraph.png
  page-navigation: true
  navbar:
    background: white
    foreground: black
    logo: images/vitae-hex.svg
    logo-alt: "Quarto Vitae"
    left:
      - href: index.qmd
        text: Home
      - href: templates.qmd
        text: Templates
      - href: using-templates.qmd
        text: Writing a CV
      - href: creating-templates.qmd
        text: Creating Templates
    right:
      - icon: github
        href: https://github.com/orgs/quarto-vitae/repositories
        aria-label: Quarto Vitae templates on GitHub

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
