#!/usr/bin/env bash
# Regenerates _templates-gallery.qmd, the auto-generated template listing
# included by templates.qmd.
#
# A repo is treated as a template if it has both a template.qmd file and a
# preview/ directory at its root (the convention documented in
# creating-templates.qmd). Templates are discovered from two places:
#
#   - every repo in the quarto-vitae GitHub org
#   - every "owner/repo" listed in templates.yml (for third-party templates)
#
# Results are cached in .cache/templates.json for CACHE_TTL seconds so that
# `quarto preview` doesn't refetch on every save. Delete the cache file, or
# set FORCE_REFRESH=1, to force a refresh.
#
# Requires: gh (authenticated: `gh auth login`), jq
set -euo pipefail

cd "$(dirname "$0")/.."

ORG="quarto-vitae"
OUT="_templates-gallery.qmd"
CONFIG="templates.yml"
CACHE=".cache/templates.json"
CACHE_TTL=1800 # seconds

command -v gh >/dev/null || { echo "generate-templates.sh: 'gh' is required" >&2; exit 1; }
command -v jq >/dev/null || { echo "generate-templates.sh: 'jq' is required" >&2; exit 1; }

mkdir -p "$(dirname "$CACHE")"

cache_age() {
  local now mtime
  now=$(date +%s)
  mtime=$(date -r "$CACHE" +%s 2>/dev/null || echo 0)
  echo $((now - mtime))
}

if [[ -f "$CACHE" && "${FORCE_REFRESH:-}" != "1" && $(cache_age) -lt "$CACHE_TTL" ]]; then
  cards=$(cat "$CACHE")
else
  echo "generate-templates.sh: fetching template list from GitHub..." >&2

  org_repos=$(gh api "orgs/$ORG/repos" --paginate --jq '.[].full_name')

  extra_repos=""
  if [[ -f "$CONFIG" ]]; then
    extra_repos=$(grep -E '^[[:space:]]*-[[:space:]]*[^[:space:]#]+/[^[:space:]#]+' "$CONFIG" \
      | sed -E 's/^[[:space:]]*-[[:space:]]*//; s/[[:space:]]*(#.*)?$//' || true)
  fi

  all_repos=$(printf '%s\n%s\n' "$org_repos" "$extra_repos" | grep -v '^[[:space:]]*$' | sort -u)

  cards="[]"
  while IFS= read -r full_name; do
    [[ -z "$full_name" ]] && continue
    owner="${full_name%%/*}"
    repo="${full_name#*/}"

    meta=$(gh api "repos/$full_name" 2>/dev/null) || { echo "  skip $full_name (not found)" >&2; continue; }
    branch=$(jq -r '.default_branch' <<<"$meta")

    tree=$(gh api "repos/$full_name/git/trees/$branch?recursive=1" 2>/dev/null) || { echo "  skip $full_name (no tree)" >&2; continue; }

    has_template=$(jq -r '[.tree[]? | select(.path=="template.qmd")] | length' <<<"$tree")
    has_preview=$(jq -r '[.tree[]? | select(.path=="preview" and .type=="tree")] | length' <<<"$tree")
    if [[ "$has_template" -lt 1 || "$has_preview" -lt 1 ]]; then
      continue
    fi

    images=$(jq -r --arg owner "$owner" --arg repo "$repo" --arg branch "$branch" \
      '[.tree[]? | select(.path | test("^preview/[^/]+\\.(png|jpe?g|svg|webp)$"; "i")) | .path]
       | sort
       | map("https://raw.githubusercontent.com/" + $owner + "/" + $repo + "/" + $branch + "/" + .)' \
      <<<"$tree")

    title=$(gh api "repos/$full_name/readme" -H "Accept: application/vnd.github.raw" 2>/dev/null \
      | grep -m1 -E '^#[[:space:]]' | sed -E 's/^#[[:space:]]+//' || true)
    [[ -z "$title" ]] && title="$repo"

    description=$(jq -r '.description // ""' <<<"$meta")
    html_url=$(jq -r '.html_url' <<<"$meta")
    official=false
    [[ "$owner" == "$ORG" ]] && official=true

    card=$(jq -n --arg title "$title" --arg repo "$full_name" --arg desc "$description" \
      --arg url "$html_url" --argjson images "$images" --argjson official "$official" \
      '{title:$title, repo:$repo, description:$desc, url:$url, images:$images, official:$official}')

    cards=$(jq --argjson c "$card" '. + [$c]' <<<"$cards")
    echo "  found $full_name" >&2
  done <<<"$all_repos"

  cards=$(jq 'sort_by([(.official | not), (.title | ascii_downcase)])' <<<"$cards")
  echo "$cards" > "$CACHE"
fi

n=$(jq 'length' <<<"$cards")
echo "generate-templates.sh: writing $OUT ($n templates)" >&2

{
  echo "<!-- Generated by scripts/generate-templates.sh. Do not edit by hand. -->"
  echo

  if [[ "$n" -eq 0 ]]; then
    echo "::: {.callout-warning}"
    echo "No templates were found. If this is unexpected, check that gh is"
    echo "authenticated and that templates.yml points at valid repos."
    echo ":::"
  else
    echo '::: {.template-grid}'
    echo

    jq -c '.[]' <<<"$cards" | while IFS= read -r card; do
      title=$(jq -r '.title' <<<"$card")
      repo=$(jq -r '.repo' <<<"$card")
      desc=$(jq -r '.description' <<<"$card")
      url=$(jq -r '.url' <<<"$card")
      official=$(jq -r '.official' <<<"$card")
      image=$(jq -r '.images[0] // empty' <<<"$card")

      echo '::: {.template-card}'
      if [[ -n "$image" ]]; then
        echo "<a href=\"${url}\"><img class=\"template-preview\" src=\"${image}\" alt=\"${title} preview\"></a>"
      fi
      echo
      if [[ "$official" == "true" ]]; then
        echo "#### [${title}](${url})"
      else
        echo "#### [${title}](${url}) [community]{.template-badge}"
      fi
      echo
      [[ -n "$desc" ]] && echo "$desc"
      echo
      echo ':::'
      echo
    done

    echo ':::'
  fi
} >"$OUT"
